<%@ Page Title="" Language="C#" MasterPageFile="~/View/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="Sellers.aspx.cs" Inherits="OnlineGroceryManagementSystem.View.Admin.Sellers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Mybody" runat="server">
    <div class="container-fluid">
        <div class="row">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-8">
                    
                    <img src="../../Assets/images/veg_food_icon-removebg-preview.png" height="90px" width="90px" /><h3 class="text-success">Manage Products</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h2 class="text-success">Sellers Details</h2>

                <div class="mb-3">
                    <label>Selller Name:</label>
                    <asp:TextBox ID="txtSelname" CssClass="form-control" runat="server"></asp:TextBox>
                </div>
                <div class="mb-3">
                    <label>Sellers Email:</label>
                    <asp:TextBox ID="txtSelemail" CssClass="form-control" runat="server"></asp:TextBox>
                </div>
                <div class="mb-3">
                    <label>Seller Password:</label>
                    <asp:TextBox ID="txtSelpass" CssClass="form-control" runat="server" ></asp:TextBox>
                </div>
                <div class="mb-3">
                    <label>Seller Phone:</label>
                    <asp:TextBox ID="txtSelphone" CssClass="form-control" runat="server"></asp:TextBox>
                </div>
                <div class="mb-3">
                    <label>Seller Address:</label>
                    <asp:TextBox ID="txtSeladd" runat="server" CssClass="form-control"></asp:TextBox>
                </div>

                <label id="lblMsg" runat="server" class="text-success"></label><br /><br />
                <asp:Button ID="btnEdit" runat="server" Text="   Edit   " class="btn btn-success" OnClick="btnEdit_Click" />
                <asp:Button ID="btnSave" runat="server" Text="   Save   " class="btn btn-success" OnClick="btnSave_Click"/>
            </div>
            <div class="col-md-8">
                <asp:GridView ID="dtgSeller" runat="server" class="table table-hover" AutoGenerateSelectButton="True" OnSelectedIndexChanged="dtgSeller_SelectedIndexChanged" AutoGenerateDeleteButton="True" OnRowDeleting="dtgSeller_RowDeleting"></asp:GridView>
            </div>
        </div>
    </div>
</asp:Content>
